Disable unavailable backends and display control functionality
The only CV backend we make an extra effort for is PyTorch since
we only have to adjust TLS certificate (not recommended but can
give us coverage until fixed upstream) in order to download any
pretrained models. To enable it, adjust the SSL context for unit
tests involving our DL backend to counter problems with PyTorch's
downloaded models and weights data like:

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)>